# Generated by Django 4.1.1 on 2022-10-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pdesc', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('cat', models.CharField(max_length=20)),
            ],
        ),
    ]
