# Generated by Django 4.1.1 on 2022-11-02 04:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_product_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('obj1', django.db.models.manager.Manager()),
            ],
        ),
    ]
