# Generated by Django 4.1.1 on 2022-11-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_product_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
